### ISSUE TITLE
Trouble during run

### ISSUE THREAD

**Issue by hasubasic** [JiatongBao/DRLSorting#3]
Hi JiatongBao, i tried to run this code, but i had few issues. 

One of them was this one: 
Traceback (most recent call last):
  File "/home/hs/DRLSorting/main.py", line 768, in <module>
    main(args)
  File "/home/hs/DRLSorting/main.py", line 30, in main
    disturb_num = args.disturb_num
                  ^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'disturb_num'

After that i put comment on line 31 and on line 363 and 364 then i got more issues>

Connected to simulation.
Traceback (most recent call last):
  File "/home/hs/DRLSorting/main.py", line 768, in <module>
    main(args)
  File "/home/hs/DRLSorting/main.py", line 77, in main
    robot = Robot(is_sim, obj_mesh_dir, num_obj, fixed_color, workspace_limits,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/DRLSorting/robot.py", line 83, in __init__
    self.setup_sim_camera()
  File "/home/hs/DRLSorting/robot.py", line 218, in setup_sim_camera
    self.bg_color_img, self.bg_depth_img = self.get_camera_data()
                                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hs/DRLSorting/robot.py", line 387, in get_camera_data
    color_img = color_img.astype(np.float)/255
                                 ^^^^^^^^
  File "/home/hs/anaconda3/lib/python3.12/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
    
 Could you help me with this? Thanks

**Comment by DucNguyenAIML** [comment]
> Hi JiatongBao, i tried to run this code, but i had few issues.
> 
> One of them was this one: Traceback (most recent call last): File "/home/hs/DRLSorting/main.py", line 768, in main(args) File "/home/hs/DRLSorting/main.py", line 30, in main disturb_num = args.disturb_num ^^^^^^^^^^^^^^^^ AttributeError: 'Namespace' object has no attribute 'disturb_num'
> 
> After that i put comment on line 31 and on line 363 and 364 then i got more issues>
> 
> Connected to simulation. Traceback (most recent call last): File "/home/hs/DRLSorting/main.py", line 768, in main(args) File "/home/hs/DRLSorting/main.py", line 77, in main robot = Robot(is_sim, obj_mesh_dir, num_obj, fixed_color, workspace_limits, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/hs/DRLSorting/robot.py", line 83, in **init** self.setup_sim_camera() File "/home/hs/DRLSorting/robot.py", line 218, in setup_sim_camera self.bg_color_img, self.bg_depth_img = self.get_camera_data() ^^^^^^^^^^^^^^^^^^^^^^ File "/home/hs/DRLSorting/robot.py", line 387, in get_camera_data color_img = color_img.astype(np.float)/255 ^^^^^^^^ File "/home/hs/anaconda3/lib/python3.12/site-packages/numpy/**init**.py", line 324, in **getattr** raise AttributeError(**former_attrs**[attr]) AttributeError: module 'numpy' has no attribute 'float'. `np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here. The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?
> 
> Could you help me with this? Thanks

Hello. I'm not Jiatongbao. However, I have experience in working on his project. You can try my solution.
The first one, **disturb_num** is nomally a "White variable". It means **disturb_num** takes no affect to the program. So you can normally give it value zero **(disturb_num = 0)**

Second, with numpy version 1.20 or higher, the command **np.float** is deprecated and can not be used anymore. You have 2 solutions to solve this problem:

1. Uninstall your numpy and reinstall the previous version of numpy, which can use **np.float**
**pip install --force-reinstall numpy==1.xx.xx**

2. You use **np.float64** instead of **np.float**

P/s: My English is not perfect, I'm still learning, if you don't understand any information, feel free to ask again.

**Comment by hasubasic** [comment]
Hi DucNguyenAIML, 

thank you form your comment. I was able to run this code.

**Comment by Mickeyyyang** [comment]
when try to train, have some error:
```bash
Training iteration: 161
success count: 1 / 10
Change detected: False (value: 243)
get label value for action grasp and then backpropagate
Current reward: 0.000000
Future reward: 0.000000
Expected reward: 0.000000 + 0.650000 x 0.000000 = 0.000000
Action: grasp at (15, 168, 184)
Executing: grasp at (-0.356000, 0.112000, 0.027154)
Training loss: 2.722512
Experience replay: iteration 101 , action: grasp, surprise value: 1.355165
Training loss: 0.123467
Grasp successful: True
Grasp correct: False
Grasp Object Color: 6
Because the correctly placed object has been grasped, reset the scene!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xuyang/miniforge3/envs/drl_sort/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/home/xuyang/miniforge3/envs/drl_sort/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xuyang/xuyang_ws/DRL/DRLSorting/main.py", line 266, in process_actions
    robot.add_objects()
  File "/home/xuyang/xuyang_ws/DRL/DRLSorting/robot.py", line 268, in add_objects
    curr_shape_handle = ret_ints[0]
IndexError: list index out of range
```

CoppeliaSim software is dump:

![Image](https://github.com/user-attachments/assets/e102c992-e2df-48ca-87eb-754b64f07748)
